version: '2'
services:
  couchdb:
    image: 'couchdb:1.6.1' 
    hostname: couchdb.server
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    ports:
      - '5984:5984'
  api:
    build: './server'
    volumes:
      - './server:/usr/app'
    ports:
      - '3000:3000'